#ifndef Bio_Resources_INCLUDED
#define Bio_Resources_INCLUDED


typedef enum UIResources_
{
	  ID_LOG_AUI = 10001
	,	ID_SETTINGS_MAIN
	, ID_TABCONTROL_MAIN
	, ID_TOOLBAR_MAIN
	, ID_APPLICATION

	, ID_GENERAL_SETTINGS_PAGE
	, ID_FACE_SETTINGS_PAGE
	, ID_FINGER_SETTINGS_PAGE
	, ID_IRIS_SETTINGS_PAGE

	, ID_PERSON_INFO_PAGE
	, ID_FACE_INFO_PAGE
	, ID_IRIS_INFO_PAGE
	, ID_FINGERPRINT_INFO_PAGE

	, ID_DEVICE_SETTINGS
	, ID_GENERAL_SETTINGS
	, ID_FACE_SETTINGS
	, ID_SEARCH_SETTINGS
	, ID_FACE_INFORMATION


} UIResources;

typedef enum UIMainMenu_
{ 
	  ID_FILE = 201
	, ID_EDIT
	, ID_VIEW
	, ID_HELP
	, ID_EXIT
	, ID_TOOLBAR
	, ID_SETTINGS
	, ID_ABOUT
	, ID_OUTPUT_WINDOW


} UIMainMenu;

typedef enum UIBioProfilePage_
{
	  ID_BTN_EDIT = 401
	, ID_BTN_OPEN
	, ID_BTN_SAVE
	, ID_BTN_DELETE
	, ID_AVATAR


} UIBioProfilePage;

typedef enum UIBioFacePage_
{
	
	  ID_BTN_ENROLL_FROM_CAMERA = 501
	, ID_BTN_ENROLL_FROM_IMAGE
	, ID_BTN_FACE_DELETE
	, ID_FACE_AVATAR
	, ID_STATUS_IMAGE

} UIBioFacePage;

typedef enum UIBioSurveillancePage_
{

	//ID_BTN_ENROLL_FROM_CAMERA = 601



} UIBioSurveillancePage;

typedef enum UIBioJournalPage_
{


	  ID_BTN_JOURNAL_DELETE = 801
	, ID_BTN_JOURNAL_DELETE_ALL


} UIBioJournalPage;

typedef enum UIBioUsersPage_
{


	ID_BTN_ADD_USER = 901
	


} UIBioUsersPage;

typedef enum UIBioLocation_
{
		
	  ID_TXT_LOCATION_NAME = 701
	, ID_TXT_TIME
	, ID_TXT_CAMERA_INFO
	
	, ID_IMG_STREAM
	, ID_IMG_ON_AIR_FIRST
	, ID_IMG_ON_AIR_SECOND
	, ID_IMG_DOOR
	, ID_IMG_CONTROLLER_STATUS_FIRST
	, ID_IMG_CONTROLLER_STATUS_SECOND
	, ID_IMG_FACE_CHECKER
	, ID_IMG_CONTROLL_BUTTON
	  

} UIBioLocation;


typedef enum UIToolbar_
{
	  ID_MAIN_SETTINGS = 301
	, ID_JOURNAL
	, ID_USERS
	, ID_PERSONAL	

} UIToolbar;

typedef enum UIBioSettings_
{
	

	//general settings
		ID_MATCHING_THRESHOLD = 20001
	,	ID_EMAIL_NOTIFICATION
	, ID_MAXIMAL_RESULT_COUNT
	, ID_RETURN_MATCHING_DETAILS
	, ID_MATCHING_FIRST_RESULT_ONLY

	,	ID_SETTINGS_BTN_APPLY
	,	ID_SETTINGS_BTN_OK
	,	ID_SETTINGS_BTN_RESET_TO_DEFAULT

	//face settings
	, ID_CAMERA
	, ID_FORMAT
	, ID_TEMPLATE_SIZE
	, ID_MATCHING_SPEED
	, ID_MINIMAL_INTER_OCULAR_DISTANCE
	, ID_CONFIDENCE_TRESHOLD
	, ID_MAXIMAL_ROLL
	, ID_MAXIMAL_YAW
	, ID_QUALITY_TRESHOLD
	, ID_GENERALIZATION_RECORD
	, ID_USE_LIVENESS_CHECK
	, ID_LIVENESS_THRESHOLD
	, ID_DETECT_ALL_FEATURE_POINTS
	, ID_DETECT_BASE_FEATURE_POINTS
	, ID_DETERMINE_GENDER
	, ID_DETECT_PROPERTIES
	, ID_RECOGNIZE_EXPRESSIONS
	, ID_RECOGNIZE_EMOTIONS
	, ID_CREATE_THUMBNAIL_IMAGE
	, ID_THUMBNAIL_IMAGE_WIDTH

} UIBioSettings;


typedef enum UIBioDeviceSettings_
{

	  ID_DEVICE_SETTINGS_PORT_NAME = 21001
	, ID_DEVICE_SETTINGS_BAUD_RATE
	

} UIBioDeviceSettings;


typedef enum UIBioFaceSettings_
{

		ID_FACE_AGE_TRESHOLD = 22001
	, ID_FACE_FACE_CONFIDENCE
	, ID_FACE_MIN_EYE_DISTANCE
	, ID_FACE_MAX_EYE_DISTANCE
	, ID_FACE_MATCHING_TRESHOLD


} UIBioFaceSettings;

typedef enum UIBioSearchSettings_
{

		ID_SEARCH_SETTINGS_DATE_TIME =23001
	, ID_SEARCH_SETTINGS_DATE_FROM
	, ID_SEARCH_SETTINGS_DATE_TO
	, ID_SEARCH_SETTINGS_TODAY
	, ID_SEARCH_SETTINGS_YESTERDAY
	, ID_SEARCH_SETTINGS_LAST_WEEK
	, ID_SEARCH_SETTINGS_LAST_MONTH
	
	, ID_SEARCH_SETTINGS_LOCATION
	, ID_SEARCH_SETTINGS_LOCATIONS
	 
	, ID_SEARCH_SETTINGS_PERSON_INFORMATION
	, ID_SEARCH_SETTINGS_FIRST_NAME
	, ID_SEARCH_SETTINGS_LAST_NAME
  
	, ID_SEARCH_SETTINGS_BY_FACE
	, ID_SEARCH_SETTINGS_BY_FACE_AGE
	, ID_SEARCH_SETTINGS_BY_FACE_IMEAGE
	, ID_SEARCH_SETTINGS_BY_FACE_FACE_CONFIDENCE



} UIBioSearchSettings;

typedef enum UIBioFaceInformationSettings_
{
		ID_FACE_INFORMATION_NUMBER_OF_FACES = 24001
	, ID_FACE_INFORMATION_NATURAL_SKIN_COLOR
	, ID_FACE_INFORMATION_GENDER
	, ID_FACE_INFORMATION_AGE
	, ID_FACE_INFORMATION_GLASSES
	, ID_FACE_INFORMATION_RESOLURION
	, ID_FACE_INFORMATION_ETHNICITY



} UIBioFaceInformationSettings;





#endif