#ifndef Bio_Resources_INCLUDED
#define Bio_Resources_INCLUDED


typedef enum UIResources_
{
	  ID_LOG_AUI = 10001
	,	ID_SETTINGS_MAIN
	, ID_TABCONTROL_MAIN
	, ID_TOOLBAR_MAIN
	, ID_APPLICATION
	, ID_SETTINGS_TAB

	, ID_GENERAL_SETTINGS_PAGE
	, ID_FACE_SETTINGS_PAGE
	, ID_FINGER_SETTINGS_PAGE
	, ID_IRIS_SETTINGS_PAGE

	, ID_PERSON_INFO_PAGE
	, ID_FACE_INFO_PAGE
	, ID_IRIS_INFO_PAGE
	, ID_FINGERPRINT_INFO_PAGE

	, ID_DEVICE_SETTINGS
	, ID_GENERAL_SETTINGS
	, ID_FACE_SETTINGS
	, ID_SEARCH_SETTINGS
	, ID_FACE_INFORMATION


} UIResources;

typedef enum UIMainMenu_
{ 
	  ID_FILE = 201
	, ID_EDIT
	, ID_VIEW
	, ID_HELP
	, ID_EXIT
	, ID_TOOLBAR
	, ID_SETTINGS
	, ID_ABOUT
	, ID_OUTPUT_WINDOW


} UIMainMenu;

typedef enum UIBioProfilePage_
{
	  ID_BTN_REFRESH = 401
	,	ID_BTN_PROFILE_ADD_USER
	, ID_BTN_OPEN
	, ID_BTN_SAVE
	, ID_BTN_DELETE
	, ID_AVATAR
	, ID_BIO_PERSON_GENDER
	, ID_BIO_PERSON_RIGTS
	, ID_BIO_PERSON_FIRST_NAME
	, ID_BIO_PERSON_LAST_NAME
	, ID_BIO_PERSON_DATE_OF_BIRTH
	, ID_BIO_PERSON_COUNTRY
	, ID_BIO_PERSON_CITY
	, ID_BIO_PERSON_COMMENTS
	, ID_BIO_PERSON_EMAIL
	, ID_BIO_PERSON_ETNICITY
	, ID_BIO_PERSON_INFO_BAR_UPD_MSG

} UIBioProfilePage;

typedef enum UIBioFacePage_
{
	
	  ID_BTN_ENROLL_FROM_CAMERA = 501
	, ID_BTN_ENROLL_FROM_IMAGE
	, ID_BTN_FACE_DELETE
	, ID_PERSON_FACE_IMAGE
	, ID_STATUS_IMAGE
	, ID_FACE_NUMBER_OF_FACES
	, ID_FACE_NATURAL_SKIN_COLOR
	, ID_FACE_GENDER
	, ID_FACE_AGE
	, ID_FACE_GLASSES
	, ID_FACE_RESOLURION
	, ID_FACE_ETHNICITY
	, ID_FACE_PAGE_NAME
	, ID_FACE_PAGE_PHOTO_PATH
	, ID_FACE_SAMPLE_QUALITY

} UIBioFacePage;

typedef enum UIBioSurveillancePage_
{
	

} UIBioSurveillancePage;

typedef enum UIBioJournalPage_
{
	  ID_BTN_JOURNAL_DELETE = 801
	, ID_BTN_JOURNAL_DELETE_ALL
	, ID_JOURNAL_PERSON_NAME
	, ID_JOURNAL_LOCATION
	, ID_JOURNAL_TIME
	, ID_JOURNAL_PHOTO              
	, ID_JOURNAL_FULL_PHOTO         
	, ID_JOURNAL_STATUS             
	, ID_JOURNAL_DETECTED_FACE_COUNT
	, ID_JOURNAL_MENU_OPEN_PERSON
	, ID_JOURNAL_MENU_DELETE_RECORD
	, ID_BTN_JOURNAL_AVATAR

} UIBioJournalPage;

typedef enum UIBioUsersPage_
{
	ID_BTN_ADD_USER = 901
	, ID_BIO_USERS_FIRST_NAME
	, ID_BIO_USERS_LAST_NAME
	, ID_BIO_USERS_DATE_OF_BIRTH
	, ID_BIO_USERS_GENDER
	, ID_BIO_USERS_COUNTRY
	, ID_BIO_USERS_CITY
	, ID_BIO_USERS_AVATAR
	, ID_BIO_USERS_PHOTO
	, ID_BIO_USERS_EMAIL
	, ID_BIO_USERS_COMMENTS
	, ID_BIO_USERS_RIGHTS
	, ID_BIO_USERS_MENU_OPEN
	, ID_BIO_USERS_MENU_ADD_NEW

} UIBioUsersPage;

typedef enum UIBioLocation_
{
		
	  ID_TXT_LOCATION_NAME = 701
	, ID_TXT_TIME
	, ID_TXT_CAMERA_INFO
	
	, ID_IMG_STREAM
	, ID_IMG_ON_AIR_FIRST
	, ID_IMG_ON_AIR_SECOND
	, ID_IMG_DOOR
	, ID_IMG_CONTROLLER_STATUS_FIRST
	, ID_IMG_CONTROLLER_STATUS_SECOND
	, ID_IMG_FACE_CHECKER
	, ID_IMG_CONTROLL_BUTTON
	  

} UIBioLocation;


typedef enum UIToolbar_
{
	  ID_MAIN_SETTINGS = 301
	, ID_JOURNAL
	, ID_USERS
	, ID_PERSONAL	

} UIToolbar;

typedef enum UIBioSettings_
{
	

	//general settings
		ID_MATCHING_THRESHOLD = 20001
	,	ID_EMAIL_NOTIFICATION
	, ID_MAXIMAL_RESULT_COUNT
	, ID_RETURN_MATCHING_DETAILS
	, ID_MATCHING_FIRST_RESULT_ONLY
	, ID_LOCATION_CAMERA_NAME

	,	ID_SETTINGS_BTN_APPLY
	,	ID_SETTINGS_BTN_OK
	,	ID_SETTINGS_BTN_RESET_TO_DEFAULT

	//face settings
	, ID_CAMERA
	, ID_FORMAT
	, ID_TEMPLATE_SIZE
	, ID_MATCHING_SPEED
	, ID_MINIMAL_INTER_OCULAR_DISTANCE
	, ID_CONFIDENCE_TRESHOLD
	, ID_MAXIMAL_ROLL
	, ID_MAXIMAL_YAW
	, ID_QUALITY_TRESHOLD
	, ID_GENERALIZATION_RECORD
	, ID_USE_LIVENESS_CHECK
	, ID_LIVENESS_THRESHOLD
	, ID_DETECT_ALL_FEATURE_POINTS
	, ID_DETECT_BASE_FEATURE_POINTS
	, ID_DETERMINE_GENDER
	, ID_DETECT_PROPERTIES
	, ID_RECOGNIZE_EXPRESSIONS
	, ID_RECOGNIZE_EMOTIONS
	, ID_CREATE_THUMBNAIL_IMAGE
	, ID_THUMBNAIL_IMAGE_WIDTH

} UIBioSettings;





typedef enum UIBioLocationSettings_
{

		ID_FACE_AGE_TRESHOLD = 22001
	, ID_FACE_FACE_CONFIDENCE
	, ID_FACE_MIN_EYE_DISTANCE
	, ID_FACE_MAX_EYE_DISTANCE
	, ID_FACE_MATCHING_TRESHOLD
	, ID_DEVICE_SETTINGS_PORT_NAME
	, ID_DEVICE_SETTINGS_LOCATION_NAME
	, ID_DEVICE_SETTINGS_BAUD_RATE

	, ID_DEVICE_SETTINGS_GENERAL
	, ID_DEVICE_SETTINGS_CAMERA
	, ID_DEVICE_SETTINGS_DEVICE
	, ID_DEVICE_SETTINGS_DETECTOR

} UIBioLocationSettings;

typedef enum UIBioSearchSettings_
{

		ID_SEARCH_SETTINGS_DATE_TIME =23001
	, ID_SEARCH_SETTINGS_DATE_FROM
	, ID_SEARCH_SETTINGS_DATE_TO
	, ID_SEARCH_SETTINGS_TODAY
	, ID_SEARCH_SETTINGS_YESTERDAY
	, ID_SEARCH_SETTINGS_LAST_WEEK
	, ID_SEARCH_SETTINGS_LAST_MONTH
	
	, ID_SEARCH_SETTINGS_LOCATION
	, ID_SEARCH_SETTINGS_LOCATIONS
	 
	, ID_SEARCH_SETTINGS_PERSON_INFORMATION
	, ID_SEARCH_SETTINGS_FIRST_NAME
	, ID_SEARCH_SETTINGS_LAST_NAME
  
	, ID_SEARCH_SETTINGS_BY_FACE
	, ID_SEARCH_SETTINGS_BY_FACE_AGE
	, ID_SEARCH_SETTINGS_BY_FACE_IMEAGE
	, ID_SEARCH_SETTINGS_BY_FACE_FACE_CONFIDENCE



} UIBioSearchSettings;

typedef enum UIBioFaceInformationSettings_
{
		ID_FACE_INFORMATION_NUMBER_OF_FACES = 24001
	, ID_FACE_INFORMATION_NATURAL_SKIN_COLOR
	, ID_FACE_INFORMATION_GENDER
	, ID_FACE_INFORMATION_AGE
	, ID_FACE_INFORMATION_GLASSES
	, ID_FACE_INFORMATION_RESOLURION
	, ID_FACE_INFORMATION_ETHNICITY
	
} UIBioFaceInformationSettings;





#endif