#ifndef Bio_Resources_INCLUDED
#define Bio_Resources_INCLUDED


typedef enum UIResources_
{
	  ID_LOG_AUI = 10001
	,	ID_SETTINGS_MAIN
	, ID_TABCONTROL_MAIN
	, ID_TOOLBAR_MAIN
	, ID_APPLICATION

	, ID_GENERAL_SETTINGS_PAGE
	, ID_FACE_SETTINGS_PAGE
	, ID_FINGER_SETTINGS_PAGE
	, ID_IRIS_SETTINGS_PAGE

	, ID_PERSON_INFO_PAGE
	, ID_FACE_INFO_PAGE
	, ID_IRIS_INFO_PAGE
	, ID_FINGERPRINT_INFO_PAGE


} UIResources;

typedef enum UIMainMenu_
{ 
	  ID_FILE = 201
	, ID_VIEW
	, ID_HELP
	, ID_EXIT
	, ID_TOOLBAR
	, ID_SETTINGS
	, ID_ABOUT
	, ID_OUTPUT_WINDOW


} UIMainMenu;


typedef enum UIToolbar_
{
	  ID_MAIN_SETTINGS = 301
	, ID_JOURNAL
	, ID_USERS
	, ID_PERSONAL	

} UIToolbar;

typedef enum UIBioSettings_
{
	//general settings
	  ID_MATCHING_THRESHOLD = 20001
	, ID_MAXIMAL_RESULT_COUNT
	, ID_RETURN_MATCHING_DETAILS
	, ID_MATCHING_FIRST_RESULT_ONLY

	//face settings
	, ID_CAMERA
	, ID_FORMAT
	, ID_TEMPLATE_SIZE
	, ID_MATCHING_SPEED
	, ID_MINIMAL_INTER_OCULAR_DISTANCE
	, ID_CONFIDENCE_TRESHOLD
	, ID_MAXIMAL_ROLL
	, ID_MAXIMAL_YAW
	, ID_QUALITY_TRESHOLD
	, ID_GENERALIZATION_RECORD
	, ID_USE_LIVENESS_CHECK
	, ID_LIVENESS_THRESHOLD
	, ID_DETECT_ALL_FEATURE_POINTS
	, ID_DETECT_BASE_FEATURE_POINTS
	, ID_DETERMINE_GENDER
	, ID_DETECT_PROPERTIES
	, ID_RECOGNIZE_EXPRESSIONS
	, ID_RECOGNIZE_EMOTIONS
	, ID_CREATE_THUMBNAIL_IMAGE
	, ID_THUMBNAIL_IMAGE_WIDTH

} UIBioSettings;





#endif